# Generated by Django 5.2.11 on 2026-05-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notification'),
        ('accounts', '0002_profile'),
    ]

    operations = [
    ]
