# Generated by Django 5.2.11 on 2026-06-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='online_connections_count',
            field=models.IntegerField(default=0),
        ),
    ]
