# Generated by Django 5.2.7 on 2026-08-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_online_connections_count'),
        ('accounts', '0005_notification'),
    ]

    operations = [
    ]
