# Generated by Django 5.2.11 on 2026-05-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('INFO', 'Information'), ('REMINDER', 'Reminder'), ('LIVE', 'Join Now'), ('SUBSCRIPTION', 'Subscription')], default='INFO', max_length=15),
        ),
    ]
