# Generated by Django 5.2.11 on 2026-08-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_admin_conversation_is_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
