# Generated by Django 5.2.17 on 2026-08-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
