"""
Django settings for Backend project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
from decouple import config
import os
import sys

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent


# =====================================================
# SECURITY
# =====================================================

SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-change-this-secret-key"
)

DEBUG = os.getenv("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    ".onrender.com",
    ".ngrok-free.dev",
    
]

SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"


# =====================================================
# INSTALLED APPS
# =====================================================

INSTALLED_APPS = [

    # Admin UI
    "jazzmin",

    # ASGI / WebSocket
    "daphne",

    # Django Core Apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",

    # Third Party Apps
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "django_extensions",
    "storages",
    "anymail",
    "channels",

    # Local Apps
    "accounts",
    "subscriptions",
    "storage",
    "chat",
    "tickets",
    "admin_management",
    "sharing",
    "notifications",
    "events",
    "assistant",
]


# =====================================================
# MIDDLEWARE
# =====================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    # CORS
    "corsheaders.middleware.CorsMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",

    "backend.middleware.MediaFrameOptionsMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# =====================================================
# CORS
# =====================================================

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True


# You do NOT need this when CORS_ALLOW_ALL_ORIGINS=True,
# but keeping localhost values is fine.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://192.168.8.105:8081",
    "http://127.0.0.1:8081",
]


CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",

    # Render deployment
    "https://*.onrender.com",
    
    # ngrok tunneling
    "https://*.ngrok-free.dev",
    
    
]



CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG

CSRF_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SAMESITE = "None"

CSRF_USE_SESSIONS = False


# =====================================================
# URL CONFIG
# =====================================================

ROOT_URLCONF = "backend.urls"


# =====================================================
# TEMPLATES
# =====================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [],

        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# =====================================================
# WSGI / ASGI
# =====================================================

WSGI_APPLICATION = "backend.wsgi.application"
ASGI_APPLICATION = "backend.asgi.application"


# =====================================================
# CHANNELS
# =====================================================

if DEBUG:

    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }

else:

    # For now use memory layer on Render too.
    # Later you can connect Render Redis.
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }


# =====================================================
# DATABASE - POSTGRESQL
# =====================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",

        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}


# =====================================================
# PASSWORD VALIDATION
# =====================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        "NAME":
        "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },

    {
        "NAME":
        "django.contrib.auth.password_validation.MinimumLengthValidator"
    },

    {
        "NAME":
        "django.contrib.auth.password_validation.CommonPasswordValidator"
    },

    {
        "NAME":
        "django.contrib.auth.password_validation.NumericPasswordValidator"
    },
]


# =====================================================
# AUTHENTICATION
# =====================================================

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]


# =====================================================
# INTERNATIONALIZATION
# =====================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Colombo"

USE_I18N = True

USE_TZ = True


# =====================================================
# STATIC FILES
# =====================================================

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"


# =====================================================
# DEFAULT PRIMARY KEY
# =====================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =====================================================
# PAYHERE
# =====================================================

PAYHERE_MERCHANT_ID = os.getenv(
    "PAYHERE_MERCHANT_ID",
    "1237637"
)

PAYHERE_MERCHANT_SECRET = os.getenv(
    "PAYHERE_MERCHANT_SECRET",
    "MzQ4MjE5MzA2MzM2MDI2OTE3MDY1MTIwMzY4MTcyNTI4Mjc2NjI0"
)

PAYHERE_SANDBOX = os.getenv(
    "PAYHERE_SANDBOX",
    "True"
).lower() == "true"


# =====================================================
# REST FRAMEWORK
# =====================================================

REST_FRAMEWORK = {

    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],

    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],

    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
}


# =====================================================
# FRONTEND DOMAIN
# =====================================================

DOMAIN = os.getenv(
    "FRONTEND_URL",
    "http://localhost:3000"
)


# =====================================================
# JWT
# =====================================================

SIMPLE_JWT = {

    "ACCESS_TOKEN_LIFETIME":
        timedelta(minutes=60),

    "REFRESH_TOKEN_LIFETIME":
        timedelta(days=7),

    "AUTH_HEADER_TYPES":
        ("Bearer",),
}


# =====================================================
# DIGITALOCEAN SPACES
# =====================================================

DO_ACCESS_KEY_ID = os.getenv(
    "DO_ACCESS_KEY_ID"
)

DO_SECRET_ACCESS_KEY = os.getenv(
    "DO_SECRET_ACCESS_KEY"
)

DO_STORAGE_BUCKET_NAME = os.getenv(
    "DO_STORAGE_BUCKET_NAME",
    "ceynoa-storage"
)

DO_S3_REGION_NAME = os.getenv(
    "DO_S3_REGION_NAME",
    "sfo3"
)

DO_S3_ENDPOINT_URL = os.getenv(
    "DO_S3_ENDPOINT_URL",
    "https://sfo3.digitaloceanspaces.com"
)


DO_DEFAULT_ACL = "private"

DO_QUERYSTRING_AUTH = True

DO_QUERYSTRING_EXPIRE = 300

DO_S3_FILE_OVERWRITE = False

DO_LOCATION = "uploads"


DO_S3_OBJECT_PARAMETERS = {
    "CacheControl": "max-age=86400",
}


# =====================================================
# AWS S3 GLACIER
# =====================================================

AWS_GLACIER_ACCESS_KEY_ID = os.getenv(
    "AWS_GLACIER_ACCESS_KEY_ID",
    ""
)

AWS_GLACIER_SECRET_ACCESS_KEY = os.getenv(
    "AWS_GLACIER_SECRET_ACCESS_KEY",
    ""
)

AWS_GLACIER_REGION = os.getenv(
    "AWS_GLACIER_REGION",
    "eu-north-1"
)

AWS_GLACIER_BUCKET_NAME = os.getenv(
    "AWS_GLACIER_BUCKET_NAME",
    ""
)


# =====================================================
# MIGRATIONS DURING TEST
# =====================================================

class DisableMigrations:

    def __contains__(self, item):
        return True

    def __getitem__(self, item):
        return None


if "test" in sys.argv:
    MIGRATION_MODULES = DisableMigrations()


# =====================================================
# STORAGE
# =====================================================

if DEBUG:

    # LOCAL DEVELOPMENT

    MEDIA_URL = "/media/"

    MEDIA_ROOT = BASE_DIR / "media"

    STORAGES = {

        "default": {
            "BACKEND":
            "django.core.files.storage.FileSystemStorage",
        },

        "staticfiles": {
            "BACKEND":
            "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

else:

    # PRODUCTION - DIGITALOCEAN SPACES

    MEDIA_URL = (
        f"https://{DO_STORAGE_BUCKET_NAME}."
        f"{DO_S3_REGION_NAME}."
        f"digitaloceanspaces.com/"
        f"{DO_LOCATION}/"
    )

    STORAGES = {

        "default": {

            "BACKEND":
            "storages.backends.s3boto3.S3Boto3Storage",

            "OPTIONS": {

                "access_key":
                    DO_ACCESS_KEY_ID,

                "secret_key":
                    DO_SECRET_ACCESS_KEY,

                "bucket_name":
                    DO_STORAGE_BUCKET_NAME,

                "region_name":
                    DO_S3_REGION_NAME,

                "endpoint_url":
                    DO_S3_ENDPOINT_URL,

                "default_acl":
                    DO_DEFAULT_ACL,

                "querystring_auth":
                    DO_QUERYSTRING_AUTH,

                "querystring_expire":
                    DO_QUERYSTRING_EXPIRE,

                "file_overwrite":
                    DO_S3_FILE_OVERWRITE,

                "object_parameters":
                    DO_S3_OBJECT_PARAMETERS,

                "location":
                    DO_LOCATION,
            },
        },

        "staticfiles": {

            "BACKEND":
            "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }


# =====================================================
# JAZZMIN
# =====================================================

JAZZMIN_SETTINGS = {

    "site_title":
        "Ceynoa Admin",

    "site_header":
        "Ceynoa",

    "site_brand":
        "Ceynoa",

    "search_model":
        None,
}


# =====================================================
# EMAIL / RESEND
# =====================================================

RESEND_API_KEY = os.getenv(
    "RESEND_API_KEY"
)