# Generated by Django 6.0.2 on 2026-08-18 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(default='General', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('users', models.ManyToManyField(blank=True, related_name='admin_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_permissions',
                'ordering': ['category', 'code'],
            },
        ),
    ]
